Save /etc/modules-load.d/ads.conf if changing
If /etc/ads-modules.d/$(hostname).conf does not exist,
don't overwrite /etc/modules-load.d/ads.conf with viper
or titan default. This is how we can prevent the modules
list from being overwritten on lab dsms.

diff --git a/ads-daq/usr/sbin/update_modules_conf b/ads-daq/usr/sbin/update_modules_conf
--- a/ads-daq/usr/sbin/update_modules_conf
+++ b/ads-daq/usr/sbin/update_modules_conf
@@ -8,27 +8,39 @@ if ! [ -f $modf ]; then
     # try lower case
     modf=/etc/ads-modules.d/$(hostname | tr 'A-Z' 'a-z').conf
 fi
-if ! [ -f $modf ]; then
-    if grep -Fq VIPER /proc/cpuinfo; then
-        modf=/etc/ads-modules.d/viper.conf
-    elif grep -Fq TITAN /proc/cpuinfo; then
-        modf=/etc/ads-modules.d/titan.conf
+
+if false; then
+    # don't overwrite ads.conf if host modules conf file is not found
+    if ! [ -f $modf ]; then
+        if grep -Fq VIPER /proc/cpuinfo; then
+            modf=/etc/ads-modules.d/viper.conf
+        elif grep -Fq TITAN /proc/cpuinfo; then
+            modf=/etc/ads-modules.d/titan.conf
+        fi
     fi
 fi
+
+dest=/etc/modules-load.d
+dmodf=$dest/ads.conf
+
 if [ -f $modf ]; then
-    dest=/etc/modules-load.d
     [ -d $dest ] || mkdir $dest
-    dmodf=$dest/ads.conf
     if [ -f $dmodf ]; then
         if ! diff -q $dmodf $modf; then
             echo "Differences:"
-            # Don't do a diff without an || here. Otherwise
+            # Don't do a diff without an || or if check here. Otherwise
             # the non-zero return will cause a script exit
-            diff $dmodf $modf || echo "Warning, overwriting $dmodf with $modf"
+            if ! diff $dmodf $modf; then
+                echo "Saving $dmodf as $dmodf.save"
+                cp $dmodf $dmodf.save
+                echo "Warning, overwriting $dmodf with $modf"
+            fi
             cp $modf $dmodf
         fi
     else
         cp $modf $dmodf
     fi
+else
+    echo "$modf not found. $dmodf unchanged"
 fi
 
