Tweak checks for cpu type

diff --git a/isfs-daq/home/daq/isfs/bin/vio b/isfs-daq/home/daq/isfs/bin/vio
--- a/isfs-daq/home/daq/isfs/bin/vio
+++ b/isfs-daq/home/daq/isfs/bin/vio
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! grep -Fq "VIPER" /proc/cpuinfo; then
+    echo "Error: this command works only on a Eurotech VIPER"
+    exit 1
+fi
+
 # shortcut script for controlling digital I/O lines
 # on Viper CPU card.
 
