Reworked triggers in isfs-daq and eol-daq

diff --git a/isfs-daq/DEBIAN/postinst b/isfs-daq/DEBIAN/postinst
--- a/isfs-daq/DEBIAN/postinst
+++ b/isfs-daq/DEBIAN/postinst
@@ -19,7 +19,7 @@ set -e
 
 
 case "$1" in
-    configure)
+    configure|triggered )
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -36,24 +36,82 @@ esac
 
 #DEBHELPER#
 
+cf=/etc/default/nidas-daq
+
 if [ "$1" = configure ]; then
-    chown -R daq.eol /home/daq
-
+    if ! [ -f $cf ]; then
+        echo "$cf does not exist, is nidas-daq installed?"
+        exit 1
+    fi
+    . $cf
+    if [ ! $DAQ_USER ]; then
+        if fgrep -q DAQ_USER= $cf; then
+            sed -r -i -e 's/^.*DAQ_USER=.*$/DAQ_USER=daq/g' $cf
+        else
+            echo "DAQ_USER=daq" >> $cf
+        fi
+    fi
+    if [ ! $DAQ_GROUP ]; then
+        if fgrep -q DAQ_GROUP= $cf; then
+            sed -r -i -e 's/^.*DAQ_GROUP=.*$/DAQ_GROUP=eol/g' $cf
+        else
+            echo "DAQ_GROUP=daq" >> $cf
+        fi
+    fi
+    if [ ! $DAQ_GID ]; then
+        if fgrep -q DAQ_GID= $cf; then
+            sed -r -i -e 's/^.*DAQ_GID=.*$/DAQ_GID=1342/g' $cf
+        else
+            echo "DAQ_GID=1342" >> $cf
+        fi
+    fi
     update-rc.d emerald defaults
-
-    # edit /etc/default/gpsd:
-    # DEVICES="/dev/ttyS3"
-    # GPSD_OPTIONS="-b -n"
-
-    # add /etc/chrony/chrony.conf
-    # SHM1 from gpsd (if present) is from the kernel PPS_LDISC
-    # module.  It includes PPS and will be accurate to a few ns
-    # refclock SHM 1 offset 0.0 delay 0.0 refid PPS
-
-    # add to /etc/modules
-    # pps_ldisc
-
 fi
 
+if [ "$1" = configure -o "$1" = triggered ]; then
+    if ! [ -f $cf ]; then
+        echo "$cf does not exist, is nidas-daq installed?"
+        exit 1
+    fi
+    . $cf
+    # check if DAQ_GROUP exists
+    if [ ! $DAQ_USER ]; then
+        echo "DAQ_USER not found in $cf"
+        exit 1
+    fi
+    if [ ! $DAQ_GROUP ]; then
+        echo "DAQ_GROUP not found in $cf"
+        exit 1
+    fi
+    if ! grep -q "^${DAQ_GROUP}:" /etc/group; then
+        gidarg=
+        [ $DAQ_GID ] && gidarg="--gid $DAQ_GID"
+        addgroup $gidarg $DAQ_GROUP
+    fi
+    # check if DAQ_USER exists
+    if ! id $DAQ_USER > /dev/null 2>&1; then
+        # should create /home/daq
+        uidarg=
+        [ $DAQ_UID ] && uidarg="--uid $DAQ_UID"
+
+        # Package has already installed some stuff to /home/daq
+        # Save it, then restore. rsync also copies hidden files
+        # Perhaps should just copy files owned by root, since those
+        # came from the package install
+        tmpdir=$(mktemp -d /tmp/${0##*/}_XXXXXX)
+        trap "{ rm -rf $tmpdir; }" EXIT
+        if [ -d /home/$DAQ_USER ]; then
+            rsync -a /home/$DAQ_USER/ $tmpdir
+            rm -rf /home/$DAQ_USER
+        fi
+        adduser $uidarg --ingroup $DAQ_GROUP --gecos "ISFS data acq account,,," --disabled-login $DAQ_USER
+        # add to sudo group
+        adduser $DAQ_USER sudo
+        rsync -a $tmpdir/ /home/$DAQ_USER
+        chown -R $DAQ_USER /home/$DAQ_USER
+        chgrp -R $DAQ_GROUP /home/$DAQ_USER
+        echo "$DAQ_USER user added, but root must do \"passwd $DAQ_USER\" for it to be activated"
+    fi
+fi
 
 exit 0
