Reworked scripts for titan

diff --git a/eol-daq/usr/bin/titan_dio b/eol-daq/usr/bin/titan_dio
--- a/eol-daq/usr/bin/titan_dio
+++ b/eol-daq/usr/bin/titan_dio
@@ -1,79 +1,46 @@
 #!/bin/sh
 
-# shortcut script for controlling digital I/O lines on Titan via its I2C device
-# at I2C address 0x20.
+# script for controlling digital I/O lines on the
+# J3 connector of a Eurotech Titan via the Maxim MAX7313
+# I2C device at I2C address 0x20.
+
+if ! fgrep -q "Eurotech TITAN" /proc/cpuinfo; then
+    echo "Error: this command works only on a Eurotech TITAN"
+    exit 1
+fi
 
 usage ()
 {
-    local script=${0##*/}
-    echo "$script [-i] [-a] [-d] n val"
-    echo "-a: actual Pn port mapping, see below"
-    echo "-d: debug, print out register I/O"
+    echo "${0##*/} [-i] [-j] [-d] n [val]"
+    echo "-d: debug, print out I2C commands"
     echo "-i: turn port into an input"
-    echo "n: Pn if -a option, otherwise the remapped port number"
+    echo "-j: n is pin number on J3 connector, 3-10, 13-20"
+    echo "n: digital port number 0-15, or, if -j option, J3 pin number"
     echo "val=0: turn digital I/O line off"
     echo "val=1: turn digital I/O line on"
     echo "If val not specified, report current setting"
-    echo "Example:   $script 6 1"
+    echo "Example:   ${0##*/} 6 1"
     echo ""
-    echo "Titan digital I/O ports are currently wired to control these FETs.
-Pn is the signal name shown on the J3-GPIO diagram in the Titan manual.
-Note that the Pn values are offset from the J3 pin numbers.
-
-This is the port mapping if the -a (actual) option is specified:
-Pn    FET      J3pin
-0     ttyS4    3 (Pn + 3)
-1     ttyS3    4
-2     ttyS2    5
-3     ttyS1    6
-4     ETH      7
-5              8
-6     ttyS0    9
-7              10
-8              13 (Pn + 5)
-9              14
-10             15
-11    aux      16
-12             17
-13    +5V      18
-14             19
-15    DC-DC    20"
-
-    echo ""
-    echo "If the -a option is NOT used, the port numbers are remapped
-to match the FETs for serial ports 0-4:
-#     FET       J3pin
-0     ttyS0     9
-1     ttyS1     6
-2     ttyS2     5
-3     ttyS3     4
-4     ttyS4     3
-5     ETH       7
-6     aux       16
-7               10
-8     +5V       18
-9     DC-DC     20"
     exit 1
 }
-
-remap=(6 3 2 1 0 4 11 7 13 15)
-
-i2c=0x20
 
 [ $# -lt 1 ] && usage
 
 setinput=false
-actual=false
 debug=false
+j3pin=false
 
 while [ $# -gt 0 ]; do
     case $1 in
+    -a)
+        # support -a option for ISFS users
+        shift
     -i)
         setinput=true
         shift
         ;;
-    -a)
-        actual=true
+    -j)
+        j3pin=true
         shift
         ;;
     -d)
@@ -98,6 +65,15 @@ case $1 in
     ;;
 esac
 
+if $j3pin; then
+    # $j3map[$i] is the Maxim MAX7313 port number for J3 pin i
+    j3map=(-1 -1 -1 0 1 2 3 4 5 6 7 -1 -1 8 9 10 11 12 13 14 15)
+    [ $port -lt 0 -o $port -ge ${#j3map[*]} ] && usage
+    port=${j3map[$port]}
+fi
+
+[ $port -lt 0 -o $port -gt 15 ] && usage
+
 if [ $# -ge 1 ]; then
     case $1 in
     0|1)
@@ -110,13 +86,7 @@ if [ $# -ge 1 ]; then
     esac
 fi
 
-if ! $actual; then
-    if [ $port -ge ${#remap[*]} ]; then
-        echo "Only ports 0-$((${#remap[*]}-1)) are remapped. Use -a option"
-        usage
-    fi
-    port=${remap[$port]}
-fi
+i2c=0x20
 
 # Fun with bash math syntax!!!!
 
diff --git a/eol-daq/usr/bin/titan_port4 b/eol-daq/usr/bin/titan_port4
--- a/eol-daq/usr/bin/titan_port4
+++ b/eol-daq/usr/bin/titan_port4
@@ -3,11 +3,13 @@
 # Use pxaregs command to set GPIO pins that control the
 # options of ttyS4 on a Titan
 
-script=$0
-script=${script##*/}
+if ! fgrep -q "Eurotech TITAN" /proc/cpuinfo; then
+    echo "Error: this command works only on a Eurotech TITAN"
+    exit 1
+fi
 
 usage() {
-    echo "$script [q] [485|422] [ nt | t ] [ rs | ns ]
+    echo "${0##*/} [q] [485|422] [ nt | t ] [ rs | ns ]
     nt   no termination
     t    120 Ohm termination
     rs   reduced slew
diff --git a/eol-daq/usr/bin/titan_usb b/eol-daq/usr/bin/titan_usb
--- a/eol-daq/usr/bin/titan_usb
+++ b/eol-daq/usr/bin/titan_usb
@@ -1,19 +1,16 @@
 #!/bin/sh
 
+if ! fgrep -q "Eurotech TITAN" /proc/cpuinfo; then
+    echo "Error: this command works only on a Eurotech TITAN"
+    exit 1
+fi
+
 usage() {
     echo "usage: ${0##*/} port [noff]"
-    echo "usbport: 1 or 2. On the Viper interface panel port 0 is nearest the edge of the card"
+    echo "usbport: 1 or 2"
     echo "onoff: 0 (off) or 1 (onn)"
     exit 1
 }
-
-titan=false
-fgrep -q PXA270 /proc/cpuinfo && titan=true
-
-if ! $titan; then
-    echo "Power to USB ports can only be controlled on a Titan"
-    exit 1
-fi
 
 [ $# -lt 1 ] && usage
 
